sudo: false

language: go

matrix:
  include:
    - go: 1.5
      os: linux
      env: REPORT_COVERAGE=false
    - go: 1.5
      os: osx
      env: REPORT_COVERAGE=false
    - go: tip
      os: linux
      env: REPORT_COVERAGE=true
    - go: tip
      os: osx
      env: REPORT_COVERAGE=false

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - libonig-dev
      - python3.5
      - python3.5-dev
      - xclip

install:
  - ./tasks/general/ci/install.sh

script:
  - ./tasks/general/ci/run_tests.sh lib
  - ./tasks/local/ci/check_gen.sh
  - ./tasks/general/ci/check_fmt.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3e692a5224c8490f19bd
    on_success: change
    on_failure: always
    on_start: false
